name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: pytest -v
    - name: Performance test
      run: |
        python - <<'EOF'
        import time, asyncio
        from core.analytics_engine import AnalyticsEngine

        engine = AnalyticsEngine(['BTC/USDT'])
        start = time.time()
        asyncio.run(engine.analyze_once())
        duration = time.time() - start
        print('duration', duration)
        assert duration < 1.0
        EOF
